name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --base-href=/portfolio/

      - name: Deploy to GitHub Pages
        uses: angular-schule/gh-pages-action@v2
        with:
          build_folder: dist/portfolio
          repo_token: ${{ secrets.GITHUB_TOKEN }} 